services:
  redis:
    image: redis:7
    container_name: langchain-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command:
      [
        "redis-server",
        "--appendonly", "yes",
        "--save", "",
        "--stop-writes-on-bgsave-error", "no"
      ]
