services:
  redis:
    image: redis:7
    container_name: langchain-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

  chroma:
    image: chromadb/chroma
    container_name: langchain-chroma
    ports:
      - "8000:8000"
    volumes:
      - ./chroma-data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
