services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  chromadb:
    image: chromadb/chroma:0.6.3
    container_name: chromadb
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
    volumes:
      - chroma-data:/chroma/chroma

  llm:
    platform: linux/arm64/v8  # Force Apple ARM arch for Metal/MPS
    build:
      context: .
      dockerfile: models/Dockerfile
    container_name: llm
    volumes:
      - .:/app
    environment:
      - MODEL_PATH=models/Qwen3-14B-Q4_K_M.gguf
    ports:
      - "8500:8500"  # expose FastAPI server
    command: uvicorn api.llm_api:app --host 0.0.0.0 --port 8500

volumes:
  postgres-data:
  redis-data:
  chroma-data: